version: '3'
services:
  db:
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: articles
      MYSQL_ROOT_PASSWORD: test123
    ports:
      - "3306:3306"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db


